In [1]:
import numpy as np 
import pandas as pd 

#machine learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_excel('data_excel.xlsx')

In [3]:
df

,password,strength,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,kzde5577,1,NaN,NaN,NaN,NaN,NaN
1,kino3434,1,NaN,NaN,NaN,NaN,NaN
2,visi7k1yr,1,NaN,NaN,NaN,NaN,NaN
3,megzy123,1,NaN,NaN,NaN,NaN,NaN
4,lamborghin1,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
669874,10redtux10,1,NaN,NaN,NaN,NaN,NaN
669875,infrared1,1,NaN,NaN,NaN,NaN,NaN
669876,184520socram,1,NaN,NaN,NaN,NaN,NaN
669877,marken22a,1,NaN,NaN,NaN,NaN,NaN
669878,fxx4pw4g,1,NaN,NaN,NaN,NaN,NaN

In [ ]:
data = df.dropna(subset=["password"])

X = data["password"]
y = data["strength"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# handle missing values with a simple imputer
imputer = SimpleImputer(strategy="constant", fill_value="")  
X_train = imputer.fit_transform(X_train.values.reshape(-1, 1)).ravel()
X_test = imputer.transform(X_test.values.reshape(-1, 1)).ravel()

vectorizer = TfidfVectorizer(analyzer="char")

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# create and train the Random Forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_tfidf, y_train)

# make predictions on the test set
predictions = model.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

password_to_check = input("Enter a password: ")
password_vector = vectorizer.transform([password_to_check])
prediction = model.predict(password_vector)[0]